### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by jessecarvalho89** [Michael-Long/FireBot#3]
There should be one of two things that happens.

1. bot not installed, prompt stating that there is nothing connected to it etc..
2. bot is installed, CMD opens up showing step by step on what to do.

This is just a thought or else everyone will just count it as broken.

                -JLC

**Comment by Michael-Long** [comment]
Yeah, with a fresh pull, it would fail to create the `config.json` file if the `data` folder didn't exist. That issue should be fixed now and it should give some better logging and error messages.
